#!/usr/bin/env python3
"""Module that retrieves a response from a LangChain language model."""


def get_response(llm, prompt):
    """Generate a response from a loaded language model.

    Args:
        llm: An instance of a LangChain LLM.
        prompt: A string containing the question or instruction for the model.

    Returns:
        AIMessage: The full response object generated by the LLM.
    """
    response = llm.invoke(prompt)
    return response
